config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items
  devise_for :users

  resources :carts, only: [:show, :destroy] do 
    resources :join_table_cart_items, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :index] do
    resources :orders, only: [:new, :create]
    resources :avatars, only: [:create]
  end

  resources :charges

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders
	
	belongs_to :customer, class_name: "User", foreign_key: "customer_id"
	
	has_many :join_table_cart_items#JoinTableCartsItems
	has_many :items, through: :join_table_cart_items#JoinTableCartItems

	def amount_to_be_paid
		self.items.sum(&:price)
	end

end

app/models/item.rb
class Item < ApplicationRecord
	has_one_attached :picture
	belongs_to :admin, class_name: "User"
	# has_many :carts
	# has_many :users, through: :carts 
	has_many :join_table_cart_items#JoinTableCartItems
	has_many :carts, through: :join_table_cart_items#JoinTableCartItems
	has_many :users, through: :carts

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
	after_create :order_send
  belongs_to :cart
  belongs_to :user

def order_send
    OrderMailer.order_email(self).deliver_now
end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  
  has_many :orders
  has_many :carts, through: :orders

	has_many :items, class_name: "Item", foreign_key: "admin_id"
  has_many :customers, class_name: "Cart", foreign_key: "cart_id"

  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_parameters, if: :devise_controller?
	before_action :set_cart

	def configure_devise_parameters
	  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
	  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :address, :last_name, :address, :current_password, :email, :password, :password_confirmation)}
	end

	private

	def set_cart
		if current_user
			@cart = Cart.find_by(customer_id: current_user.id)
			if @cart.nil?
				@cart = Cart.create(customer_id: current_user.id)
			end
		end
	end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController 
	before_action :is_the_owner_of_the_page?, only: [:show, :destroy]

    def show
      @cart=Cart.find_by(customer_id: current_user.id)
      @items=@cart.items
    end

    def create
    end

    def destroy
    end

    private

  	def is_the_owner_of_the_page?
  		unless current_user.id.to_i == @cart.customer_id.to_i
  		redirect_to items_path
  		end
  	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount,
	    description: 'Rails Stripe customer',
	    currency: 'usd',
	  })

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item=Item.new
	end 

	def create
		@item=Item.new(title: params[:title], description: params[:description], price: params[:price], picture: params[:picture], admin: current_user)
		if @item.save
			redirect_to item_path(@item.id)
			flash[:success] = "This kitty has been successfully added to the kitty database"
		else
			flash[:error] = "Something went wrong, please try again"
			render :new
		end
	end

	def edit
		@item=Item.find(params[:id])
	end 

	def update
		@item=Item.find(params[:id])
		if @item.update(item_params)
		redirect_to item_path(@item.id)
		flash[:success] = "This page has been successfully modified !"
		else
		flash[:error] = "Something went wrong, please try again"
		render :edit
		end 
	end

	def destroy
		@item=Item.find(params[:id])
		@item.destroy
		redirect_to request.referrer
		flash[:success]= "You have successfully deleted this cat"
	end 
	 
	private

	def item_params
		item_params=params.require(:item).permit(:title, :description, :price, :picture)
	end

end

app/controllers/join_table_cart_items_controller.rb
class JoinTableCartItemsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @additem = JoinTableCartItem.new(cart_id: @cart.id, item_id: params[:item])
      
    if @additem.save
      flash[:success] = 'This item was added to your cart'
      redirect_to request.referrer ### REDIRECT TO SAME PAGE
    else
      flash[:error] = 'There was a problem adding this item to your cart'
      redirect_to request.referrer
    end
  end

  def destroy
    @cart = Cart.find_by(customer_id: current_user.id)
    @item_to_destroy = JoinTableCartItem.find_by(cart_id: params[:cart_id], item_id: params[:id])
    @item_to_destroy.destroy
    flash[:success] = 'This item has been deleted from your cart'
    redirect_to cart_path(@cart.id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@orders = params[:user_id].orders
	end

	def new
	end

	def create
	  @amount = @cart.amount_to_be_paid*100 # amount in cents
	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })
	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount.to_i,
	    description: 'Rails Stripe customer',
	    currency: 'eur',
		})
    @order = Order.new(
			user_id: @cart.customer_id,
			cart_id: @cart.id,
			delivery_address: "test adresse",
			items_number: @cart.items.length,
			total_order: @amount/100
		)
		if @order.save
			@cart.destroy
			#redirect_to user_path(current_user.id)
		else
		 render :back
		end

		rescue Stripe::CardError => e
			flash[:error] = e.message
			redirect_to new_charge_path
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
	before_action :is_the_owner_of_the_page?, only: [:show]

	def show
		@user = User.find(params[:id])
		@orders = Order.where(user_id: params[:id])
		@items = Item.where(admin_id: params[:id])
	end

	private

  	def is_the_owner_of_the_page?
  		unless current_user.id.to_i == params[:id].to_i
  		redirect_to items_path
  		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/join_table_cart_items_helper.rb
module JoinTableCartItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_show.html.erb
<tr class="g-brd-bottom g-brd-gray-light-v3">
    <td class="text-left g-py-25">
    <%if item.picture.attached?%>
        <%= image_tag item.picture, alt: 'picture', class: "d-inline-block g-width-100 mr-4" %>
    <%else%>
        <img class="d-inline-block g-width-100 mr-4" src="<%=item.image_url%>" alt="Image Description">
    <%end%>
    <div class="d-inline-block align-middle">
        <h4 class="h6 g-color-black"> <%=item.title%></h4>
        <ul class="list-unstyled g-color-gray-dark-v4 g-font-size-12 g-line-height-1_6 mb-0">
        <li><%=item.price%> €</li>
        </ul>
    </div>
    </td>
    <td class="g-color-gray-dark-v2 g-font-size-13"><%=item.price%> €</td>
    <td>
    <div class="js-quantity input-group u-quantity-v1 g-width-80 g-brd-primary--focus">
        <input class="js-result form-control text-center g-font-size-13 rounded-0 g-pa-0" type="text" value="1" readonly="">

        <div class="input-group-addon d-flex align-items-center g-width-30 g-brd-gray-light-v2 g-bg-white g-font-size-12 rounded-0 g-px-5 g-py-6">
        <i class="js-plus g-color-gray g-color-primary--hover fa fa-angle-up"></i>
        <i class="js-minus g-color-gray g-color-primary--hover fa fa-angle-down"></i>
        </div>
    </div>
    </td>
    <td class="text-right g-color-black">
    <span class="g-color-gray-dark-v2 g-font-size-13 mr-4"><%=item.price%> €</span>
    <span class="g-color-gray-dark-v4 g-color-black--hover g-cursor-pointer">
         <%= link_to cart_join_table_cart_item_path(@cart.id, item.id), {"method" => "delete"} , class:"g-color-gray-dark-v5 g-color-primary--hover g-text-underline--none--hover" do %> 
         <i class="mt-auto fa fa-trash"></i>
         <% end %>
    </span>
    </td>
</tr>

app/views/carts/show.html.erb
<div class="container g-pt-100 g-pb-70">

  <% if @items.empty? %>

    <div class="container text-center g-py-100">
      <div class="mb-5">
        <span class="d-block g-color-gray-light-v1 g-font-size-70 g-font-size-90--md mb-4">
          <i class="fas fa-shopping-cart fa-1x"></i>
        </span>
        <h2 class="g-mb-30">Your Cart is Currently Empty</h2>
        <p>Before proceed to checkout you must add some products to your shopping cart.<br>You will find a lot of interesting products on our "Shop" page.</p>
      </div>
      <a class="btn u-btn-primary g-font-size-12 text-uppercase g-py-12 g-px-25" href="/items">Start Shopping</a>
    </div>

  <% else %>

  <form class="js-validate js-step-form" data-progress-id="#stepFormProgress" data-steps-id="#stepFormSteps" novalidate="novalidate">
    <div class="g-mb-100">
    <!-- Step Titles -->
    <ul id="stepFormProgress" class="js-step-progress row justify-content-center list-inline text-center g-font-size-17 mb-0">
        <li class="col-3 list-inline-item g-mb-20 g-mb-0--sm active">
        <span class="d-block u-icon-v2 u-icon-size--sm g-rounded-50x g-brd-primary g-color-primary g-color-white--parent-active g-bg-primary--active g-color-white--checked g-bg-primary--checked mx-auto mb-3">
            <i class="g-font-style-normal g-font-weight-700 g-hide-check">1</i>
            <i class="fa fa-check g-show-check"></i>
        </span>
        <h4 class="g-font-size-16 text-uppercase mb-0">Shopping Cart</h4>
        </li>

        <li class="col-3 list-inline-item g-mb-20 g-mb-0--sm">
        <span class="d-block u-icon-v2 u-icon-size--sm g-rounded-50x g-brd-gray-light-v2 g-color-gray-dark-v5 g-brd-primary--active g-color-white--parent-active g-bg-primary--active g-color-white--checked g-bg-primary--checked mx-auto mb-3">
            <i class="g-font-style-normal g-font-weight-700 g-hide-check">2</i>
            <i class="fa fa-check g-show-check"></i>
        </span>
        <h4 class="g-font-size-16 text-uppercase mb-0">Payment</h4>
        </li>
    </ul>
    <!-- End Step Titles -->
    </div>

    <div id="stepFormSteps">
    <!-- Shopping Cart -->
    <div id="step1" class="active">
      <div class="row">
        <div class="col-md-8 g-mb-30">
            <!-- Products Block -->
            <div class="g-overflow-x-scroll g-overflow-x-visible--lg">
            <table class="text-center w-100">
                <thead class="h6 g-brd-bottom g-brd-gray-light-v3 g-color-black text-uppercase">
                <tr>
                    <th class="g-font-weight-400 text-left g-pb-20">Product</th>
                    <th class="g-font-weight-400 g-width-130 g-pb-20">Price</th>
                    <th class="g-font-weight-400 g-width-50 g-pb-20">Qty</th>
                    <th class="g-font-weight-400 g-width-130 g-pb-20">Total</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                <!-- Item-->
                <% @items.each do |item|%>
                    <%= render 'show', item: item %>
                <% end %>
                </tbody>
            </table>
            </div>
            <!-- End Products Block -->
        </div>

        <div class="col-md-4 g-mb-30">
        <!-- Summary -->
          <div class="g-bg-gray-light-v5 g-pa-20 g-pb-50 mb-4">
            <h4 class="h6 text-uppercase mb-3">Summary</h4>
            <div class="row">
              <% @items.each do |item| %>
                <div class="col-md-12 d-flex justify-content-between">
                  <span class="g-color-black"><%=item.title%></span>
                  <span class="g-color-black g-font-weight-300"><%=item.price%> €</span>
                </div>
              <%end%>
              </div>
              <hr>
              <div class="d-flex justify-content-between">
                    <span class="g-color-black">Order Total</span>
                    <span class="g-color-black g-font-weight-800"><%= @cart.amount_to_be_paid %> €</span>
              </div><hr>
              <%= link_to "Proceed to payment" , new_user_order_path(current_user.id), class:"btn btn-block u-btn-primary g-font-size-13 text-uppercase g-py-15 mb-4" %>
          </div>
        </div>
        <!-- End Summary -->
      </div>
    <!-- End Shopping Cart -->
    </div>
    </div>

    <!-- Payment & Review -->
    <div id="step3" style="display: none;">
      <div class="row">
        <div class="col-md-8 g-mb-30">
            <!-- Payment Methods -->
            <ul class="list-unstyled mb-5">
            <li class="g-brd-bottom g-brd-gray-light-v3 pb-3 my-3">
                <label class="form-check-inline u-check d-block u-link-v5 g-color-gray-dark-v4 g-color-primary--hover g-pl-30">
                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" name="radInline1_1" type="radio">
                    <span class="d-block u-check-icon-checkbox-v4 g-absolute-centered--y g-left-0">
                    <i class="fa" data-check-icon=""></i>
                    </span>
                    Pay with
                <img class="g-width-70 ml-2" src="assets/img-temp/200x55/img1.jpg" alt="Image Description">
                </label>
            </li>
            <li class="my-3">
                <label class="form-check-inline u-check d-block u-link-v5 g-color-gray-dark-v4 g-color-primary--hover g-pl-30">
                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" name="radInline1_1" type="radio" checked="">
                    <span class="d-block u-check-icon-checkbox-v4 g-absolute-centered--y g-left-0">
                    <i class="fa" data-check-icon=""></i>
                    </span>
                    Pay with Credit Card
                <img class="g-width-50 ml-2" src="assets/img-temp/200x55/img2.jpg" alt="Image Description">
                </label>
            </li>
            </ul>
            <!-- End Payment Methods -->

            <!-- Alert -->
            <div class="alert g-brd-around g-brd-gray-dark-v5 rounded-0 g-pa-0 mb-4" role="alert">
              <div class="media">
                  <div class="d-flex g-brd-right g-brd-gray-dark-v5 g-pa-15">
                  <span class="u-icon-v1 u-icon-size--xs g-color-black">
                      <i class="align-middle icon-media-065 u-line-icon-pro"></i>
                  </span>
                  </div>
                  <div class="media-body g-pa-15">
                  <p class="g-color-black m-0">My billing and shipping address are the correct</p>
                  </div>
              </div>
            </div>
            <!-- End Alert -->
        </div>
      </div>
    </div>

  </form>
<%end%>
</div>

app/views/items/index.html.erb
<!-- Hero Info -->
<section class="dzsparallaxer auto-init height-is-based-on-content use-loading" data-options='{direction: "reverse", settings_mode_oneelement_max_offset: "150"}'>
  <!-- Parallax Image -->
  <div class="divimage dzsparallaxer--target w-100 u-bg-overlay g-bg-black-opacity-0_2--after" style="height: 140%; background-image: url(https://images.unsplash.com/photo-1570018144715-43110363d70a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1860&q=80)"></div>
  <!-- End Parallax Image -->

  <div class="container text-center g-color-white g-py-150--md g-py-80">
    <div class="row">
      <div class="col-md-8 ml-md-auto mr-md-auto">
        <h3 class="g-font-size-12 text-uppercase g-font-weight-600 g-mb-15"> <span class="g-color-primary">Our</span> Kitten</h3>
          <a href="#all-items" class="btn btn-md u-btn-primary g-mr-10 g-mb-15">Shop Now</a>
        <a href="#contact-info" class="btn btn-md u-btn-outline-primary g-mr-10 g-mb-15 u-btn-hover-v2-1 g-mr-10 g-mb-15">Contact Us</a>
        <h2 class="h1 text-uppercase mb-3"></h2>
        <div class="d-inline-block g-width-60 g-height-1 g-bg-white mb-3"></div>
        <p class="lead g-mb-60"><br><br><br><br><br><br><br><br><br> </p>
      </div>
    </div>
  </div>
</section>
    <!-- Hero Info -->

<!-- Features -->
<div class="g-brd-bottom g-brd-gray-light-v4">
  <div class="container g-py-30">
    <div class="row justify-content-center">
      <div class="col-md-4 mx-auto g-py-15">
        <div class="media g-px-50--lg">
          <i class="d-flex g-color-black g-font-size-30 g-pos-rel g-top-3 mr-4 fas fa-truck fa-7"></i>
          <div class="media-body">
            <span class="d-block g-font-weight-500 g-font-size-default text-uppercase">Free Shipping</span>
            <span class="d-block g-color-gray-dark-v4">In 2-3 Days</span>
          </div>
        </div>
      </div>

      <div class="col-md-4 mx-auto g-brd-x--md g-brd-gray-light-v3 g-py-15">
        <div class="media g-px-50--lg">
          <i class="d-flex g-color-black g-font-size-30 g-pos-rel g-top-3 mr-4 fas fa-dolly fa-7"></i>
          <div class="media-body">
            <span class="d-block g-font-weight-500 g-font-size-default text-uppercase">Free Returns</span>
            <span class="d-block g-color-gray-dark-v4">No Questions Asked</span>
          </div>
        </div>
      </div>

      <div class="col-md-4 mx-auto g-py-15">
        <div class="media g-px-50--lg">
          <i class="d-flex g-color-black g-font-size-30 g-pos-rel g-top-3 mr-4 fas fa-exclamation fa-7"></i>
          <div class="media-body text-left">
            <span class="d-block g-font-weight-500 g-font-size-default text-uppercase">Free 24</span>
            <span class="d-block g-color-gray-dark-v4">Days Storage</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Features -->

<!-- New Arrivals -->
<section class="container g-py-80" id="all-items" >
  <div class="text-center mx-auto g-max-width-600 g-mb-80">
    <h2 class="g-color-black mb-4">New Arrivals</h2>
    <p class="lead">We want to offer you the cutest kitten photo ever. Once you will hang it in your living-room, it will brighten your day!</p>
  </div>

  <div class="row g-mx-minus-10 g-mb-50">
  <% @items.each do |item|%>
    <div class="col-md-6 col-lg-4 g-px-10">
      <!-- Article -->
      <article class="media g-brd-around g-brd-gray-light-v4 g-bg-white rounded g-pa-10 g-mb-20">
        <!-- Article Image -->
        <div class="g-max-width-100 g-mr-15">
          <%if item.picture.attached?%>
            <%= image_tag item.picture, alt: 'picture', class: "d-flex w-100" %>
          <%else%>
            <img class="d-flex w-100" src="<%=item.image_url%>" alt="Image Description">
          <%end%>
        </div>
        <!-- End Article Image -->

        <!-- Article Info -->
        <div class="media-body align-self-center">
          <h4 class="h5 g-mb-7">
            <a class="g-color-black g-color-primary--hover g-text-underline--none--hover" href="#"><%= link_to item.title, item_path(item.id)%></a>
          </h4>
          <a class="d-inline-block g-color-gray-dark-v5 g-font-size-13 g-mb-10" href="#">Kitten photo</a>
          <!-- End Article Info -->

          <!-- Article Footer -->
          <footer class="d-flex justify-content-between g-font-size-16">
            <span class="g-color-black g-line-height-1"><%= item.price %>€</span>
            <ul class="list-inline g-color-gray-light-v2 g-font-size-14 g-line-height-1">
              <li class="list-inline-item align-middle g-brd-right g-pr-10 g-mr-6">
                
              <% if user_signed_in? %>
                <%= link_to cart_join_table_cart_items_path(@cart.id, "item" => item.id), {"method" => "post"} , class:"g-color-gray-dark-v5 g-color-primary--hover g-text-underline--none--hover" do %>
                  <i class="fas fa-shopping-bag fa-7"></i>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path , class:"g-color-gray-dark-v5 g-color-primary--hover g-text-underline--none--hover" do %>
                  <i class="fas fa-shopping-bag fa-7"></i>
                <% end %>
              <% end %>

              </li>
            </ul>
          </footer>
          <!-- End Article Footer -->
        </div>
      </article>
      <!-- End Article -->
    </div>
  <% end %>
  </div>
</section>
<!-- End New Arrivals -->

<!-- Promo Block -->
<section class="dzsparallaxer auto-init height-is-based-on-content use-loading mode-scroll loaded dzsprx-readyall " data-options='{direction: "fromtop", animation_duration: 25, direction: "reverse"}'>
  <!-- Parallax Image -->
  <div class="divimage dzsparallaxer--target w-100 g-bg-cover g-bg-size-cover g-bg-pos-top-center g-bg-black-opacity-0_3--after" style="height: 140%; background-image: url(https://images.unsplash.com/photo-1545529468-42764ef8c85f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2252&q=80);"></div>
  <!-- End Parallax Image -->

  <!-- Promo Block Content -->
  <div class="container g-color-white text-center g-py-150">
    <h2 class="h3 text-uppercase mb-2"></h2>
    <p class="g-font-weight-600 g-font-size-40 text-uppercase"><br></p>
  </div>
  <!-- Promo Block Content -->
</section>
<!-- End Promo Block -->


<div class="container g-py-60" id="contact-info">
  <!-- Contact Info -->
  <div class="row g-mb-20">
    <div class="col-md-6 col-lg-4 mx-auto g-py-15">
      <!-- Media -->
      <div class="media g-brd-around g-brd-gray-light-v4 rounded g-pa-40">
        <div class="d-flex g-mr-30">
          <i class="d-inline-block g-color-primary g-font-size-40 g-pos-rel g-top-3 fas fa-phone"></i>
        </div>
        <div class="media-body">
          <span class="d-block g-font-weight-500 g-font-size-default text-uppercase mb-2">The team</span>
          <span class="d-block g-color-gray-dark-v4">Jade Caillot, Fleur Himmler, Mathieu Farge, et Jonas Audia</span>
        </div>
      </div>
      <!-- End Media -->
    </div>

    <div class="col-md-6 col-lg-4 mx-auto g-py-15">
      <!-- Media -->
      <div class="media g-brd-around g-brd-gray-light-v4 rounded g-pa-40">
        <div class="d-flex g-mr-30">
          <i class="d-inline-block g-color-primary g-font-size-40 g-pos-rel g-top-3 fas fa-map-marked-alt"></i>
        </div>
        <div class="media-body">
          <span class="d-block g-font-weight-500 g-font-size-default text-uppercase mb-2">Location</span>
          <span class="d-block g-color-gray-dark-v4">The Hacking Project, 67000 Strasbourg, France</span>
        </div>
      </div>
      <!-- End Media -->
    </div>

      <!-- Media -->
      <div class="col-md-6 col-lg-4 mx-auto g-py-15">
        <div class="media g-brd-around g-brd-gray-light-v4 rounded g-pa-40">
          <div class="d-flex g-mr-30">
            <i class="d-inline-block g-color-primary g-font-size-40 g-pos-rel g-top-3 far fa-clock"></i>
          </div>
          <div class="media-body text-left">
            <span class="d-block g-font-weight-500 g-font-size-default text-uppercase mb-2">Office Hours</span>
            <ul class="list-unstyled mb-0">
              <li class="d-block g-color-gray-dark-v4">Mon - Fri: 09AM to 06PM</li>
              <li class="d-block g-color-gray-dark-v4">Sat - Sun: 10AM to 04PM</li>
            </ul>
          </div>
        </div>
        <!-- End Media -->
      </div>
    </div>
  </div>
</div>
  <!-- End Contact Info -->


  <div class="g-max-width-645 text-center mx-auto g-mb-10">
    <h2 class="h1 mb-3">Contact Us</h2>
    <p class="g-font-size-17 mb-0">Fill up the form and hit the "Send Message". One of our representatives will get back to you as soon as possible.</p>
  </div>

<div class="container g-py-80">
<!-- Contact Form -->
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <form>
        <div class="row">
          <div class="col-md-6 form-group g-mb-20">
            <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded g-py-13 g-px-15" type="text" placeholder="Name">
          </div>

          <div class="col-md-6 form-group g-mb-20">
            <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded g-py-13 g-px-15" type="email" placeholder="Email">
          </div>

          <div class="col-md-6 form-group g-mb-20">
            <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded g-py-13 g-px-15" type="text" placeholder="Subject">
          </div>

          <div class="col-md-6 form-group g-mb-20">
            <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded g-py-13 g-px-15" type="tel" placeholder="Phone">
          </div>

          <div class="col-md-12 form-group g-mb-40">
            <textarea class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover g-resize-none rounded g-py-13 g-px-15" rows="7" placeholder="Message"></textarea>
          </div>
        </div>

        <div class="text-center">
          <button class="btn u-btn-primary g-font-size-12 text-uppercase g-py-12 g-px-25" type="submit">Send Message</button>
        </div>
      </form>
    </div>
  </div>
<!-- End Contact Form -->
</div>