config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items
  devise_for :users

  resources :carts, only: [:show, :destroy] do 
    resources :join_table_cart_items, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :index] do
    resources :orders, only: [:new, :create]
    resources :avatars, only: [:create]
  end

  resources :charges

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders
	
	belongs_to :customer, class_name: "User", foreign_key: "customer_id"
	
	has_many :join_table_cart_items#JoinTableCartsItems
	has_many :items, through: :join_table_cart_items#JoinTableCartItems

	def amount_to_be_paid
		self.items.sum(&:price)
	end

end

app/models/item.rb
class Item < ApplicationRecord
	has_one_attached :picture
	belongs_to :admin, class_name: "User"
	# has_many :carts
	# has_many :users, through: :carts 
	has_many :join_table_cart_items#JoinTableCartItems
	has_many :carts, through: :join_table_cart_items#JoinTableCartItems
	has_many :users, through: :carts

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
	after_create :order_send
  belongs_to :cart
  belongs_to :user

def order_send
    OrderMailer.order_email(self).deliver_now
end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  
  has_many :orders
  has_many :carts, through: :orders

	has_many :items, class_name: "Item", foreign_key: "admin_id"
  has_many :customers, class_name: "Cart", foreign_key: "cart_id"

  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController 
	before_action :is_the_owner_of_the_page?, only: [:show, :destroy]

    def show
      @cart=Cart.find_by(customer_id: current_user.id)
      @items=@cart.items
    end

    def create
    end

    def destroy
    end

    private

  	def is_the_owner_of_the_page?
  		unless current_user.id.to_i == @cart.customer_id.to_i
  		redirect_to items_path
  		end
  	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount,
	    description: 'Rails Stripe customer',
	    currency: 'usd',
	  })

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item=Item.new
	end 

	def create
		@item=Item.new(title: params[:title], description: params[:description], price: params[:price], picture: params[:picture], admin: current_user)
		if @item.save
			redirect_to item_path(@item.id)
			flash[:success] = "This kitty has been successfully added to the kitty database"
		else
			flash[:error] = "Something went wrong, please try again"
			render :new
		end
	end

	def edit
		@item=Item.find(params[:id])
	end 

	def update
		@item=Item.find(params[:id])
		if @item.update(item_params)
		redirect_to item_path(@item.id)
		flash[:success] = "This page has been successfully modified !"
		else
		flash[:error] = "Something went wrong, please try again"
		render :edit
		end 
	end

	def destroy
		@item=Item.find(params[:id])
		@item.destroy
		redirect_to request.referrer
		flash[:success]= "You have successfully deleted this cat"
	end 
	 
	private

	def item_params
		item_params=params.require(:item).permit(:title, :description, :price, :picture)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@orders = params[:user_id].orders
	end

	def new
	end

	def create
	  @amount = @cart.amount_to_be_paid*100 # amount in cents
	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })
	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount.to_i,
	    description: 'Rails Stripe customer',
	    currency: 'eur',
		})
    @order = Order.new(
			user_id: @cart.customer_id,
			cart_id: @cart.id,
			delivery_address: "test adresse",
			items_number: @cart.items.length,
			total_order: @amount/100
		)
		if @order.save
			@cart.destroy
			#redirect_to user_path(current_user.id)
		else
		 render :back
		end

		rescue Stripe::CardError => e
			flash[:error] = e.message
			redirect_to new_charge_path
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
	before_action :is_the_owner_of_the_page?, only: [:show]

	def show
		@user = User.find(params[:id])
		@orders = Order.where(user_id: params[:id])
		@items = Item.where(admin_id: params[:id])
	end

	private

  	def is_the_owner_of_the_page?
  		unless current_user.id.to_i == params[:id].to_i
  		redirect_to items_path
  		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="g-bg-main-light-v1" style="bottom:0px; width: 100%;">
    <div class="g-brd-bottom g-brd-secondary-light-v1">

        <div class="container g-pt-50">
            <div class="row">
                <div class="col-md-4 g-mb-50">
                    <h2 class="h5 g-color-gray-light-v3 mb-4">Subscribe</h2>

                    <!-- Subscribe Form -->
                    <form class="input-group u-shadow-v19 rounded">
                    <input class="form-control g-brd-none g-color-gray-dark-v5 g-bg-main-light-v2 g-bg-main-light-v2--focus g-placeholder-gray-dark-v3 rounded g-px-20 g-py-8" type="email" placeholder="Enter your email">
                    <span class="input-group-addon u-shadow-v19 g-brd-none g-bg-main-light-v2 g-pa-5">
                        <button class="btn u-btn-primary rounded text-uppercase g-py-8 g-px-18" type="submit">
                        <i class="fa fa-angle-right"></i>
                        </button>
                    </span>
                    </form>
                    <!-- End Subscribe Form -->
                </div>

                <div class="col-6 col-md-3 offset-lg-1 g-mb-30">
                    <h2 class="h5 g-color-gray-light-v3 mb-4">Contact</h2>
                    <!-- Links -->
                    <ul class="list-unstyled g-color-gray-dark-v5 g-font-size-13">
                    <li class="media my-3">
                        <i class="d-flex mt-1 mr-3 fas fa-map-marked-alt"></i>
                        <div class="media-body">
                        Royaume des chatons, KittyCiy, NL S0B2V9
                        </div>
                    </li>
                    <li class="media my-3">
                        <i class="d-flex mt-1 mr-3 fas fa-envelope-open-text"></i>
                        <div class="media-body">
                        contact@kittycat.com
                        </div>
                    </li>
                    <li class="media my-3">
                        <i class="d-flex mt-1 mr-3 fas fa-phone"></i>
                        <div class="media-body">
                        +33 5 56 91 32 72
                        </div>
                    </li>
                    </ul>
                    <!-- End Links -->
                </div>

                <div class="col-6 col-md-3 ml-auto g-mb-30">
                    <h2 class="h5 g-color-gray-light-v3 mb-4">Follow Us On:</h2>
                    <!-- Social Icons -->
                    <ul class="list-inline mb-50">
                    <li class="list-inline-item g-mr-2">
                        <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-facebook--hover rounded" href="https://www.facebook.com/groups/kittycatclubgroup/">
                        <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fab fa-facebook-f fa-5"></i>
                        <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fab fa-facebook-f fa-5"></i>
                        </a>
                    </li>
                    <li class="list-inline-item g-mx-2">
                        <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-twitter--hover rounded" href="https://twitter.com/kitcatchronicle">
                        <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fab fa-twitter fa-5"></i>
                        <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fab fa-twitter fa-5"></i>
                        </a>
                    </li>
                    <li class="list-inline-item g-mx-2">
                        <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-instagram--hover rounded" href="https://www.instagram.com/explore/tags/kittycat/?hl=fr">
                        <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fab fa-instagram fa-5"></i>
                        <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fab fa-instagram fa-5"></i>
                        </a>
                    </li>
                    </ul>
                    <!-- End Social Icons -->
                </div>
                </div>
                <!-- End Secondary Content -->
            </div>
            </div>
            <div class="container g-pt-20 g-pb-5">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-6 g-mb-20">
                <p class="g-font-size-13 mb-0">2020 © THP Strasbourg S11. All Rights Reserved.</p>
                </div>

            <div class="col-md-6 text-md-right g-mb-10">
                <ul class="list-inline g-color-gray-dark-v5 g-font-size-25 mb-0">
                    <li class="list-inline-item g-cursor-pointer mr-1">
                        <i class="fab fa-cc-visa" title="" data-toggle="tooltip" data-placement="top" data-original-title="Visa"></i>
                    </li>
                    <li class="list-inline-item g-cursor-pointer mx-1">
                        <i class="fab fa-cc-mastercard" title="" data-toggle="tooltip" data-placement="top" data-original-title="Master Card"></i>
                    </li>
                    <li class="list-inline-item g-cursor-pointer ml-1">
                        <i class="fab fa-cc-stripe" title="" data-toggle="tooltip" data-placement="top" data-original-title="Stripe"></i>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<!------------------------------------------------------- top navbar ------------------------------------------------------------->

<div class="u-header__section g-brd-bottom g-brd-gray-light-v4 g-bg-black g-transition-0_3">
    <div class="container">
      <div class="row justify-content-between align-items-center g-mx-0--lg">
        <div class="col-sm-auto g-hidden-sm-down">
          <!-- Social Icons -->
          <ul class="list-inline g-py-14 mb-0">
            <li class="list-inline-item">
              <a class="g-color-white-opacity-0_8 g-color-primary--hover g-pa-3" href="https://www.facebook.com/groups/kittycatclubgroup/">
                <i class="fab fa-facebook-f fa-5"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="g-color-white-opacity-0_8 g-color-primary--hover g-pa-3" href="https://twitter.com/kitcatchronicle">
                <i class="fab fa-twitter fa-5"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="g-color-white-opacity-0_8 g-color-primary--hover g-pa-3" href="https://www.instagram.com/explore/tags/kittycat/?hl=fr">
                <i class="fab fa-instagram fa-5"></i>
              </a>
            </li>
          </ul>
          <!-- End Social Icons -->
        </div>

        <div class="col-sm-auto g-hidden-sm-down g-color-white-opacity-0_6 g-font-weight-400 g-pl-15 g-pl-0--sm g-py-14">
          <i class="fas fa-mobile-alt g-font-size-18 g-valign-middle g-color-white-opacity-0_8 g-mr-10 g-mt-minus-2"></i>
          +33 5 56 91 32 72
        </div>

        <div class="col-sm-auto g-pos-rel g-py-14">
          <!-- List -->
          <ul class="list-inline g-pt-1 mb-0">
            <!-- Currency -->
            <li class="list-inline-item g-pos-rel">
                <i class="g-ml-20--md mr-2 fa fa-euro"></i>
                Euro
            </li>
            <!-- End Currency -->
            <!-- Language -->
            <li class="list-inline-item g-pos-rel">
              English
            </li>
            <!-- End Language -->
          </ul>
          <!-- End List -->
        </div>
              
         <div class="col-sm-auto g-pr-0--sm mb-0">
          <!-- Basket -->
          <div class="u-basket d-inline-block g-z-index-3">
            <div class="g-py-10 g-px-6">
              <ul class="list-inline g-overflow-hidden g-pt-1 g-mx-minus-4 mb-0"></ul>
              <% if user_signed_in? %>
                <li class="list-inline-item g-mx-4">
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"btn btn-outline-primary rounded-sm g-color-secondary-opacity-0.6--hover g-font-weight-400 g-text-underline--none--hover pb-2" %> 
                </li>
                <%= link_to cart_path(cart.id), id:"basket-bar-invoker", class:"u-icon-v1 g-color-white-opacity-0_8 g-color-primary--hover g-font-size-17 g-text-underline--none--hover pb-3" do %>
                <span class="u-badge-v1--sm g-color-white g-bg-primary g-font-size-11 g-line-height-1_4 g-rounded-50x g-pa-4" style="top: 7px !important; right: 3px !important;"><%=@cart.items.count%></span>
                  <i class="fas fa-shopping-bag fa-7"></i>
                <% end %>
              <% else %>
                <li class="list-inline-item g-mx-4">
                  <%= link_to 'Signup', new_user_registration_path, class:"btn btn-outline-primary rounded-sm g-color-secondary-opacity-0.6--hover g-font-weight-400 g-text-underline--none--hover" %>
                </li>
                <li class="list-inline-item g-mx-4">
                  <%= link_to 'Login', new_user_session_path, class:"btn btn-primary rounded-sm g-color-primary--hover g-font-weight-400 g-text-underline--none--hover" %> 
                </li>
                <%= link_to new_user_session_path, id:"basket-bar-invoker", class:"u-icon-v1 g-color-white-opacity-0_8 g-color-primary--hover g-font-size-17 g-text-underline--none--hover pb-3" do %>
                  <i class="fas fa-shopping-bag fa-7"></i>
                <% end %>
              <% end %>
              </ul>
            </div>
            </div></div><div id="mCSB_1_scrollbar_vertical" class="mCSB_scrollTools mCSB_1_scrollbar mCS-minimal-dark mCSB_scrollTools_vertical" style="display: block;"><div class="mCSB_draggerContainer"><div id="mCSB_1_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; display: block; height: 91px; max-height: 166px; top: 0px;"><div class="mCSB_dragger_bar" style="line-height: 50px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div>
            </div>
          </div>
          <!-- End Basket -->
        </div>
      </div>
    </div>
  </div>
<!------------------------------------------------------- End top navbar ------------------------------------------------------------->

<!------------------------------------------------------- Second navbar ------------------------------------------------------------->
     <div class="u-header__section u-header__section--light g-bg-white g-transition-0_3 g-py-10">
          <nav class="js-mega-menu navbar navbar-expand-lg">
            <div class="container">
              <!-- Responsive Toggle Button -->
              <button class="navbar-toggler navbar-toggler-right btn g-line-height-1 g-brd-none g-pa-0 g-pos-abs g-top-3 g-right-0" type="button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="navBar" data-toggle="collapse" data-target="#navBar">
                <span class="hamburger hamburger--slider g-pr-0">
                  <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                  </span>
                </span>
              </button>
              <!-- End Responsive Toggle Button -->

      <!-- Logo -->
      <%= link_to image_tag('logo_rd.png', width: 160), root_path, class:"navbar-brand" %>
      <!-- End Logo -->

      <!-- Navigation -->
      <div id="navBar" class="collapse navbar-collapse align-items-center flex-sm-row g-pt-15 g-pt-0--lg">
        <ul class="navbar-nav ml-auto">
          <!-- Home - Submenu -->
          <li class="nav-item g-mx-10--lg g-mx-15--xl">
            <%=link_to "Home", root_path, id:"nav-link--pages", class:"nav-link text-uppercase g-color-primary--hover g-px-5 g-py-20"%>
          </li>
          <%if user_signed_in?%>
            <li class="nav-item g-mx-10--lg g-mx-15--xl">
                <%= link_to 'Your profil', user_path(current_user.id), id:"nav-link--pages", class:"nav-link text-uppercase g-color-primary--hover g-px-5 g-py-20" %>
            </li>
            <li class="nav-item g-mx-10--lg g-mx-15--xl">
              <%= link_to 'Add a kitty', new_item_path, id:"nav-link--pages", class:"nav-link g-color-primary text-uppercase g-color-primary--hover g-px-5 g-py-20" %>
          </li>
          <%end%>
          <!-- End Pages - Submenu -->
        </ul>
      </div>
      <!-- End Navigation -->
    </div>
  </nav>
</div>
<!------------------------------------------------------- End Second navbar ------------------------------------------------------------->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/da8b50c52a.js" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%if flash.any?%>
        <p class="alert alert-secondary "><%= flash[:success] || flash[:error] %></p>
    <%end%>

    <%= render "layouts/navbar" , cart: @cart %>
    <%= yield %>
    <%=render "layouts/footer"%>
  </body>
</html>